config/routes.rb
BaseballApp::Application.routes.draw do
  resources :users

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match 'help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  match '/standings', :to => 'pages#standings'
  match '/teams', :to => 'pages#teams'
  match '/signup', :to => 'users#new'
  
root :to => 'pages#home'
  
end

  
  

  
  
  

app/models/user.rb
# == Schema Information
# Schema version: 20110425202931
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  #tells database which information can be edited by outside users
  attr_accessible :name, :email
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  
  #validates the presence of a name attribute
  validates :name, :presence => true, :length => { :maximum => 50}
    #validates the presence of email attribute
  validates :email, :presence => true, :format => { :with => email_regex }, :uniqueness => { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def teams
    @title = "Teams"
  end

  def standings
    @title = "Standings"
  end

  def news
    @title = "News"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end
  
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per page basis
  def title
    base_title = "Baseball Heaven"
    if @title.nil?
      base_title 
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", news_path %></li>
      <li><%= link_to "Standings", standings_path %></li>
      <li><%= link_to "Teams", teams_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("baseball.jpg", :alt => "Baseball Heaven", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Teams", teams_path %></li>
      <li><%= link_to "Standings", standings_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
  <!-- [if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![end if]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball Heaven | <%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="containter">
      <%= render"layouts/header"%>
    <section class="round">
<%= yield %>
    </section>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>Baseball Heaven is your source for all the latest Major League Baseball news and standings.  Baseball Heaven also proudly allows users to post their thoughts on the latest baseball news!</p>
  

app/views/pages/contact.html.erb
<h1>Contact Baseball Heaven</h1>

<p>You can reach the Baseball Heaven team <a href="mailto:cody.hill07@gmail.com?subject=A meassage from a Baseball Heaven user">HERE</a></p>
  

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Get help with any problems you are having with Baseball Heaven 
  Contact us <a href="mailto:cody.hill07@gmail.com?subject=A message from a user of Baseball Heaven">HERE</a></p>

app/views/pages/home.html.erb
<h1>Home</h1>

<p>This is the home page for the <a href="http://www.baseballheaven.heroku.com">Baseball Heaven</a></p>

<%= link_to "Join us in the Dugout!", '#', :class => "signup_button round" %>

app/views/pages/news.html.erb
<h1>News</h1>

<p>Catch all the latest news from around the league!</p>
  

app/views/pages/standings.html.erb
<h1>Standings</h1>

<p>Current Standings</p>
  

app/views/pages/teams.html.erb
<h1>Teams</h1>

<center>
  <table border="1" cellpadding="0" cellspacing="0" height="750" width="900">
   <tr>
     <td colspan="2"><center>American League</center></td>
   </tr>
   <tr>
     <td colspan="2"><center>EAST</center></td>
    </tr>
   <tr>
     <td><center><img src="images/orioles.gif" width="35"></center></td>
     <td>Baltimore Orioles</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/red-sox.gif" width="35"></center></td>
      <td>Boston Red Sox</td>
    </tr>
    <tr>
      <td><center><img src="images/yankees.jpg.jpeg" width="35"></center></td>
      <td>New York Yankees</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/rays.jpeg" width="35"></center></td>
      <td>Tampa Bay Rays</td>
    </tr>
    <tr>
      <td><center><img src="images/bluejays.jpg" width="35"></center></td>
      <td>Toronto Blue Jays</td>
    </tr>
    <tr>
      <td colspan="2"><center>CENTRAL</center></td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/whitesox.jpeg" width="35"></center></td>
      <td>Chicago White Sox</td>
    </tr>
    <tr>
      <td><center><img src="images/indians.jpeg" width="35"></center></td>
      <td>Cleveland Indians</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/tigers.jpeg" width="35"></center></td>
      <td>Detroit Tigers</td>
    </tr>
    <tr>
      <td><center><img src="images/royals.jpeg" width="35"></center></td>
      <td>Kansas City Royals</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/twins.jpeg" width="35"></center></td>
      <td>Minnesota Twins</td>
    </tr>
    <tr>
      <td colspan="2"><center>WEST</center></td>
    </tr>
    <tr>
      <td><center><img src="images/angles.jpeg" width="35"></center></td>
      <td>Los Angeles Angels</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/a's.jpeg" width="35"></center></td>
      <td>Oakland Athletics</td>
    </tr>
    <tr>
      <td><center><img src="images/mariners.jpg" width="35"></cetner></td>
      <td>Seattle Mariners</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/rangers.jpeg" width="35"></center></td>
      <td>Texas Rangers</td>
    </tr>
    <tr>
      <td colspan="2"><center>National League</center></td>
    </tr>
    <tr>
      <td colspan="2"><center>EAST</central></td>
    </tr>
    <tr>
      <td><center><img src="images/braves.jpg" width="35"></center></td>
      <td>Atlanta Braves</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/marlins.jpg" width="35"></center></td>
      <td>Florida Marlins</td>
    </tr>
    <tr>
      <td><center><img src="images/mets.jpg" width="35"></center></td>
      <td>New York Mets</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/phillies.jpg.jpeg" width="35"></center></td>
      <td>Philadelphia Phillies</td>
    </tr>
    <tr>
      <td><center><img src="images/nationals.gif" width="35"></center></td>
      <td>Washington Nationals</td>
    </tr>
    <tr>
      <td colspan="2"><center>CENTRAL</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/cubs.jpeg" width="35"></center></td>
      <td>Chicago Cubs</td>
    </tr>
    <tr>
      <td><center><img src="images/reds.jpeg" width="35"></center></td>
      <td>Cincinnati Reds</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/astros.jpeg" width="35"></center></td>
      <td>Houston Astros</td>
    </tr>
    <tr>
      <td><center><img src="images/brewers.jpeg" width="35"></center></td>
      <td>Milwaukee Brewers</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/pirates.jpeg" width="35"></center></td>
      <td>Pittsburgh Pirates</td>
    </tr>
    <tr>
      <td><center><img src="images/cards.jpeg" width="35"></center></td>
      <td>St. Louis Cardinals</td>
    </tr>
    <tr>
      <td colspan="2"><center>WEST</center></td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/dbacks.jpg" width="35"></center></td>
      <td>Arizona Diamondbacks</td>
    </tr>
    <tr>
      <td><center><img src="images/rockies.jpeg" width="35"></center></td>
      <td>Colorado Rockies</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/dodgers.jpg" width="35"></center></td>
      <td>Los Angeles Dodgers</td>
    </tr>
    <tr>
      <td><center><img src="images/padres.jpeg" width="35"></center></td>
      <td>San Diego Padres</td>
    </tr>
    <tr bgcolor="DEDDD2">
      <td bgcolor="#fff"><center><img src="images/giants.jpeg" width="35"></center></td>
      <td>San Francisco Giants</td>
    </tr>
  </table>
      
    
   
    
      

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>